# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_estudiante_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_sustentacion',
        ),
    ]
