# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_estudiante_fecha_sustentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajogrado',
            name='nombre_trabajo_de_grado',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
